#version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: slang_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: slangdb
      MYSQL_USER: slanguser
      MYSQL_PASSWORD: slangpass
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    networks:
      - slang_network
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: slang_backend
    depends_on:
      - db
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://slanguser:slangpass@db/slangdb
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - slang_network
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mysql_data:
networks:
  slang_network:
